;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "deps-tree-skill")
(def path ".")
(def version "0.1.1")
(def tag "0.1.1")
(def generated-at "2021-02-03T05:59:28Z")
